### ISSUE TITLE
Unsupported model

### ISSUE THREAD

**Issue by andgenn78** [tabulartools/dax-optimizer#27]
### Describe the problem

Have similar problem for some models
• Unsupported
This model is not supported by the current version of the service or is invalid.
Do not analyze it again, report the issue instead.
Report Issue

### Power BI

Version: 2.128.1380.0 64-bit (April 2024)

### Steps to reproduce the behavior

1. Add model
2. Export model through Bravo
3. Upload model
4. Same problem with TE3

### Anything else ?

Trace id: 026e2df9-9912-42b5-f5de-bdaf4cead4a9

**Comment by albertospelta** [comment]
@andgenn78 It appears that the issue you're encountering is similar to the one reported in https://github.com/tabulartools/dax-optimizer/issues/26, possibly due to the VPAX file not containing the minimum information required for analysis. Could you please check the VPAX extraction settings in the Tabular Editor options panel to ensure they are configured as specified in https://github.com/tabulartools/dax-optimizer/issues/26#issuecomment-2102998189?

**Comment by albertospelta** [comment]
@andgenn78 We're closing this issue as telemetry indicates the problem has been resolved and the model has been successfully validated and analyzed. However, if the issue persists, please let us know here, and we can reopen the issue.
