### ISSUE TITLE
Authenticated User is not authorised

### ISSUE THREAD

**Issue by wynhopkins** [tabulartools/dax-optimizer#28]
### Describe the problem

Error DO200000: Forbidden.
Authenticated user is not authorized.
PATCH /v1/workspace/251686641678-a838b82c-5226-4415-83d5-9306b5d37ac8/model/251686638112-aabb8a6e-3c26-4646-bc45-b41b0ba7a151

### Power BI

Version: 2.128.1380.0 64-bit (April 2024)

### Steps to reproduce the behavior

New model, uploaded VPAX (extracted with Bravo), error appears
Doesn't seem to prevent further analysis or functionality

### Screenshots

![image](https://github.com/tabulartools/dax-optimizer/assets/44314473/a6e95de2-27d3-4f5b-adcf-d84fa1d2689c)

### Anything else ?

Trace id: 195e170643f3015c1bb7cbc025991d74

**Comment by albertospelta** [comment]
@wynhopkins thanks for reporting! We have identified the error and can reproduce it. We can confirm that the error only occurs during the VPAX upload, but the file is still uploaded correctly and there are no impacts on the application functionalities or model analysis results. We will close the issue once the fix is released.

**Comment by albertospelta** [comment]
Closing this as the fix has been released.
