### ISSUE TITLE
Error uploading VPAX file

### ISSUE THREAD

**Issue by MatanBaruchTempo** [tabulartools/dax-optimizer#30]
### Describe the problem

Error 500: Unknown error.
POST /v1/vpax/251687739083-3c701ade-7565-49b6-acff-28d080d15718/251680335251-bb5bf83c-ec2d-4faf-aa6f-6da0a32aa986

### Power BI

Power BI Desktop version July 2024

### Anything else ?

Trace id: b5aa7424f863e59426a2aa67789dc00b

**Comment by albertospelta** [comment]
@MatanBaruchTempo Thanks for reporting, we're currently investigating this.

**Comment by albertospelta** [comment]
@MatanBaruchTempo We've investigated the problems you've reported: `Error 500: Unknown error` and [`Failed to fetch`](https://github.com/tabulartools/dax-optimizer/issues/31).
Both issues appear to have the same underlying cause related to file upload and download operations.

Specifically, the errors occur during the upload of the VPAX file and the download of the file containing the analysis results for the sample model. Both of these files are compressed archive files in ZIP format, making them binary rather than plaintext.

Our hypothesis is that there might be some client-side security blocking these HTTP requests. This could include browser security extensions, firewalls/proxies, or antivirus that are blocking the transmission of these binary contents.

Could it be that you are using DaxOptimizer from a network where browser restrictions for this type of traffic might be in place?

To gather more information, it would be very helpful if you could perform the following test:
- open your browser in incognito mode and ensure that any security extensions installed in the browser are disabled
- launch the developer tools by pressing F12. This should open the DevTools in a new window
- log in to DaxOptimizer using your account and try to reproduce the error by uploading a VPAX file 

The console panel in the DevTools window should then display the error message along with more details about the cause. Could you send us this information, either as a screenshot or by saving the log in text format using the `Save as` option as shown in the image below? If you prefer to share the file privately, you can send it to support@tabulartools.com.

![image](https://github.com/user-attachments/assets/8cf0b1cf-ee8d-4f15-a6ba-e9e75b7ff034)

**Comment by albertospelta** [comment]
Hi @MatanBaruchTempo According to our telemetry data, it appears that a VPAX file has been successfully uploaded and analyzed. Could you please confirm if the issue has indeed been resolved on your end? Thank you!

**Comment by MatanBaruchTempo** [comment]
Hi Alberto,

Thank you for your follow-up. The issue has indeed been resolved; it was related to the firewall blocking the VPAX file upload.
You can go ahead and close the ticket. I appreciate your quick response and support in this matter.

Best regards,
