### ISSUE TITLE
Unsupported VPAX file

### ISSUE THREAD

**Issue by suketududhat** [tabulartools/dax-optimizer#44]
### Describe the problem

Getting "Unsupported" error for VPAX files uploaded from DAX Studio and TE3. I have looked at other posts in this repo and have followed the comments in https://github.com/tabulartools/dax-optimizer/issues/26#issuecomment-2102998189 but still not working for my model.

### Power BI

Power BI Fabric Capacity

### Steps to reproduce the behavior

1. Connect to my production workspace and choose a model in DAX Studio
2. Click "View Metric" and it runs successfully
3. Click "Export Metrics" and save as .vpax file
4. In app.daxoptimizer.com, click "+Version" to upload .vpax from step 3

### Screenshots

![image](https://github.com/user-attachments/assets/3e98cc32-46f4-406b-b83c-2694cfb71d95)

### Anything else ?

Region: eastus
Account: 251697547922-95c13136-128f-4196-b1f2-c4e1876798a7
Contract: 251671394097-d36c48b8-b7dc-488d-a703-b73444a695e0
Workspace: 251697547922-95c13136-128f-4196-b1f2-c4e1876798a7
Model: 251671393780-5ba9bcb6-2376-4872-9e91-a5cd5408d5f6
VPAX: 251668779598-a879b1fe-7625-46f4-aab6-f11cc69ac976

**Comment by albertospelta** [comment]
@suketududhat Based on information from our telemetry, the VPAX file being reported as unsupported is indeed due to the missing statistics from the data, just as mentioned in https://github.com/tabulartools/dax-optimizer/issues/26#issuecomment-2102998189.

Could you try re-extracting the file by following these steps?

1. Open your extraction tool (e.g., TE3 or DAX Studio).
2. Ensure the following settings are enabled (see images below for how these settings should appear in the tools):
- Statistics From Data
- Statistics From Direct Query
- Set "Statistics From Direct Lake" to "Full"

3. If these options are not active, enable them, restart the tool, and verify that the settings remain enabled after the restart.
4. Extract a new VPAX and upload the file to DAX Optimizer and please let us know if the file is still reported as unsupported. If it is, please include the VPAX ID (e.g., `VPAX: 251668779598-a879b1fe-7625-46f4-aab6-f11cc69ac976`).

> Settings for DAX Studio
![image](https://github.com/user-attachments/assets/706411e0-f9e8-43e9-bd15-1a60dff0bcb1)

> Settings for Tabular Editor 3
![image](https://github.com/user-attachments/assets/25d217c4-77c4-4a8b-995c-2e8f4d7915ce)

JFYI, if you want to verify that the options were applied during the extraction, you can:

- Rename the `.vpax` file to `.zip` and extract its contents.
- Open the `DaxModel.json` file using an editor like VSCode and ensure that the properties in `ExtractorProperties` are present and enabled as shown below.

![image](https://github.com/user-attachments/assets/7b4bb5e7-f6ad-496f-b52d-91d7b036b019)

**Comment by albertospelta** [comment]
@suketududhat As an additional note to my previous comment, if you are using DAX Studio, please check the log panel after the extraction is complete to ensure that no warning messages are being reported. If you find any warning, please let us know the details of the message. 

When the extraction is successful, the log should look like this
![image](https://github.com/user-attachments/assets/34d7028e-153c-4119-bfb7-47f13b3320fb)

**Comment by suketududhat** [comment]
@albertospelta I followed your steps to set the options in DAX Studio instead of just the export metric dialog box and it is working now. Not sure why the dialog box was not working before as I was selecting the same options before but to confirm I checked one of the vpax file to zip and it is missing the ExtractorProperties you shared above. Thank you for sharing the extra steps to troubleshoot similar issues in the future!
